services:
  - type: web
    name: streambox
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: AGAMES_URL
        value: http://11.jpn.gg:10225
