databases:
  - name: invidious-db
    databaseName: invidious
    user: kemal
    plan: free

services:
  - type: web
    name: invidious
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: INVIDIOUS_CONFIG
        value: |
          db:
            dbname: invidious
            user: kemal
            password: ${DB_PASSWORD}
            host: ${DB_HOST}
            port: 5432
          check_tables: true
          external_port: 443
          domain: ${RENDER_EXTERNAL_HOSTNAME}
          https_only: true
          statistics_enabled: false
          use_quic: false
      - key: DB_HOST
        fromDatabase:
          name: invidious-db
          property: host
      - key: DB_PASSWORD
        fromDatabase:
          name: invidious-db
          property: password
